export const RENDER_MODAL = 'RENDER_MODAL';
export const SET_ACTIVE_ORG = 'SET_ACTIVE_ORG';
export const SHOW_SPACES_THREADS = 'SHOW_SPACES_THREADS';
export const RESET_SPACE = 'RESET_SPACE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_DONE = 'RESET_PASSWORD_DONE';
