export const RENDER_MODAL = 'RENDER_MODAL';
export const RENDER_FOLLOW_UP = 'RENDER_FOLLOW_UP';
export const HIDE_FOLLOW_UP = 'HIDE_FOLLOW_UP';
export const SET_ACTIVE_ORG = 'SET_ACTIVE_ORG';
export const SET_ACTIVE_THREAD = 'SET_ACTIVE_THREAD';
export const SHOW_SPACES_THREADS = 'SHOW_SPACES_THREADS';
export const RESET_SPACE = 'RESET_SPACE';
export const RESET_THREAD = 'RESET_THREAD';
